/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 12:33:24 GMT 2025
 */

package org.apache.commons.lang3.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.lang.MockError;
import org.evosuite.runtime.mock.java.lang.MockRuntimeException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ExceptionUtils_ESTest extends ExceptionUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockThrowable0, class0, 1);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("at");
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      List<Locale.LanguageRange> list0 = Locale.LanguageRange.parse("at", (Map<String, List<String>>) hashMap0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      linkedList0.add("at");
      List<String> list1 = Locale.filterTags(list0, (Collection<String>) linkedList0, locale_FilteringMode0);
      ExceptionUtils.removeCommonFrames(list1, linkedList0);
      assertEquals(2, linkedList0.size());
      assertEquals(0, list1.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("at");
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      List<Locale.LanguageRange> list0 = Locale.LanguageRange.parse("at", (Map<String, List<String>>) hashMap0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      List<String> list1 = Locale.filterTags(list0, (Collection<String>) linkedList0, locale_FilteringMode0);
      ExceptionUtils.removeCommonFrames(list1, linkedList0);
      assertEquals(1, linkedList0.size());
      assertEquals(0, list1.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("at");
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      List<Locale.LanguageRange> list0 = Locale.LanguageRange.parse("at", (Map<String, List<String>>) hashMap0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      linkedList0.add("");
      List<String> list1 = Locale.filterTags(list0, (Collection<String>) linkedList0, locale_FilteringMode0);
      ExceptionUtils.removeCommonFrames(list1, linkedList0);
      assertTrue(list1.contains("at"));
      assertEquals(1, list1.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("[Q`uO)iiV");
      linkedList0.add("");
      ExceptionUtils.removeCommonFrames(linkedList0, linkedList0);
      assertFalse(linkedList0.contains("[Q`uO)iiV"));
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockThrowable0, (Class<? extends Throwable>) class0, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockError mockError0 = new MockError(", Length: 0");
      MockError mockError1 = new MockError(mockError0);
      MockError mockError2 = new MockError("", mockError1);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("^;4?E$$?qq");
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockError2, (PrintWriter) mockPrintWriter0);
      assertFalse(mockError1.equals((Object)mockError2));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockError mockError0 = new MockError();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("X M8eg'MbWmHiGO#", mockError0);
      String string0 = ExceptionUtils.getRootCauseMessage(mockRuntimeException0);
      assertEquals("MockError: ", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockThrowable0, class0, (-1089));
      assertSame(throwable0, mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockRuntimeException0, "getLinkedException");
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException1 = ExceptionUtils.throwableOfThrowable((Throwable) undeclaredThrowableException0, class0);
      assertSame(mockRuntimeException0, mockRuntimeException1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<Throwable> class0 = Throwable.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockError0, (Class<? extends Throwable>) class0, (-1579));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockError0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("u$T.bt-#a5lz*");
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("QG[n L$:", mockThrowable0);
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, (-2525));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockThrowable0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockError> class0 = MockError.class;
      boolean boolean0 = ExceptionUtils.hasCause(mockError0, class0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables((Throwable) null);
      assertEquals(0, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      List<Throwable> list0 = ExceptionUtils.getThrowableList((Throwable) null);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      int int0 = ExceptionUtils.getThrowableCount(mockThrowable0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      List<String> list0 = ExceptionUtils.getStackFrameList(mockRuntimeException0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockThrowable0);
        fail("Expecting exception: Throwable");
      
      } catch(Throwable e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add((String) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrames(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrames((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.StringTokenizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrameList(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getRootCauseStackTrace(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("u$T.bt-#a5lz*");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      MockPrintStream mockPrintStream0 = new MockPrintStream(byteArrayOutputStream0);
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintStream) mockPrintStream0);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: u$T.bt-#a5lz*\n", byteArrayOutputStream0.toString());
      assertEquals(65, byteArrayOutputStream0.size());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockError0, (PrintStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The PrintStream must not be null
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintStream) null);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      List<Throwable> list0 = ExceptionUtils.getThrowableList(mockThrowable0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException("", mockRuntimeException0);
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace(mockRuntimeException1);
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Throwable throwable0 = ExceptionUtils.getRootCause((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MockError mockError0 = new MockError();
      Throwable throwable0 = ExceptionUtils.getRootCause(mockError0);
      assertSame(mockError0, throwable0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MockError mockError0 = new MockError();
      String string0 = ExceptionUtils.getMessage(mockError0);
      assertEquals("MockError: ", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      String string0 = ExceptionUtils.getMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockThrowable0, (String[]) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("");
      MockThrowable mockThrowable0 = new MockThrowable(mockRuntimeException0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockThrowable0, (String[]) null);
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) null, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      String string0 = ExceptionUtils.getStackTrace(mockThrowable0);
      //  // Unstable assertion: assertEquals("sun.reflect.GeneratedConstructorAccessor125.newInstance(Unknown Source)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MockError mockError0 = new MockError("org");
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables(mockError0);
      assertEquals(1, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockThrowable0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      Class<MockThrowable> class0 = MockThrowable.class;
      MockThrowable mockThrowable1 = ExceptionUtils.throwableOfThrowable((Throwable) mockThrowable0, class0, (-2050));
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: ", mockThrowable1.toString());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockError mockError0 = new MockError();
      MockThrowable mockThrowable0 = new MockThrowable(mockError0);
      Class<MockError> class0 = MockError.class;
      MockError mockError1 = ExceptionUtils.throwableOfType((Throwable) mockThrowable0, class0);
      assertSame(mockError0, mockError1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) null, class0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("[y-.P+2gRx!b*");
      LinkedList<String> linkedList1 = new LinkedList<String>();
      ExceptionUtils.removeCommonFrames(linkedList0, linkedList1);
      assertEquals(0, linkedList1.size());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      StackTraceElement stackTraceElement0 = new StackTraceElement("", "", "f5vNS<AW}BK^+G~M~", 1437);
      StackTraceElement stackTraceElement1 = new StackTraceElement("at", "", (String) null, 5);
      MockError mockError0 = new MockError(mockThrowable0);
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[7];
      stackTraceElementArray0[0] = stackTraceElement1;
      stackTraceElementArray0[1] = stackTraceElement0;
      stackTraceElementArray0[2] = stackTraceElement0;
      stackTraceElementArray0[3] = stackTraceElement0;
      stackTraceElementArray0[4] = stackTraceElement0;
      stackTraceElementArray0[5] = stackTraceElement0;
      stackTraceElementArray0[6] = stackTraceElement0;
      mockError0.setStackTrace(stackTraceElementArray0);
      List<String> list0 = ExceptionUtils.getStackFrameList(mockError0);
      assertFalse(list0.isEmpty());
      
      ExceptionUtils.removeCommonFrames(list0, list0);
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames((List<String>) null, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintWriter) null);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockThrowable0, (PrintWriter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The PrintWriter must not be null
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      MockError mockError0 = new MockError();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("X M8eg'MbWmHiGO#", mockError0);
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockThrowable0, (Class<? extends Throwable>) class0, (-1061));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockError0, (Class<? extends Throwable>) class0, 2);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      int int0 = ExceptionUtils.indexOfType((Throwable) mockThrowable0, (Class<? extends Throwable>) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException((Throwable) null);
      boolean boolean0 = ExceptionUtils.hasCause(undeclaredThrowableException0, class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException(mockThrowable0);
      mockThrowable0.initCause(mockRuntimeException0);
      List<Throwable> list0 = ExceptionUtils.getThrowableList(mockThrowable0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      String[] stringArray0 = ExceptionUtils.getStackFrames(mockThrowable0);
      assertEquals(6, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("at");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("");
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      String string0 = ExceptionUtils.getRootCauseMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      MockError mockError0 = new MockError();
      String[] stringArray0 = new String[4];
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockError0, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockThrowable mockThrowable1 = new MockThrowable(mockThrowable0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockThrowable1);
      assertNotNull(throwable0);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable", throwable0.toString());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockThrowable0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      MockError mockError0 = new MockError();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("$+C5opqT", mockError0);
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("u$T.bt-#a5lz*");
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) null, class0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      int int0 = ExceptionUtils.getThrowableCount((Throwable) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      ExceptionUtils exceptionUtils0 = new ExceptionUtils();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      MockError mockError0 = new MockError((String) null);
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, class0, 3061);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      Class<MockError> class0 = MockError.class;
      MockError mockError0 = ExceptionUtils.throwableOfType((Throwable) mockThrowable0, class0);
      assertNull(mockError0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getDefaultCauseMethodNames();
      MockThrowable mockThrowable0 = new MockThrowable();
      MockError mockError0 = new MockError(mockThrowable0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockError0, stringArray0);
      assertSame(mockThrowable0, throwable0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("u$T.bt-#a5lz*");
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockRuntimeException0, (Class<Throwable>) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockError0, class0, (-1349));
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockError mockError0 = new MockError("?WUK'8D19I;q|CXyI:_", mockRuntimeException0);
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockError0, "LaunchTime");
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) undeclaredThrowableException0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockError mockError0 = new MockError("?WUK'8D19I;q|CXyI:_", mockRuntimeException0);
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockError0, "LaunchTime");
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0, (-2031));
      assertEquals(1, int0);
  }
}
